### ISSUE TITLE
Picodrive sega32x

### ISSUE THREAD

**Issue by aksenav2** [Rezzy-dev/picodrive#1]
Hello, sega32x games on picodrive 1.93 are freezing and slowing down. Console xyc q8 and fc3000. On picodrive version 1.99 it is better, but the emulator itself is buggy. Is there any way to solve this problem?

**Comment by Rezzy-dev** [comment]
This version of PicoDrive was never good at running Sega 32X or Sega CD games (that side of the emulation was incomplete) -- it's for standard Sega Mega Drive (Genesis) games, that's what it emulates well.

You may want to check out this enhancement project:

https://github.com/irixxxx/picodrive

This is an effort to complete/improve Sega 32X and Sega CD emulation on PicoDrive (among other enhancements).

**Comment by aksenav2** [comment]
> 

Sega cd works fine.

**Comment by aksenav2** [comment]
Okay, thanks for the advice.
